name: journal-service

services:

  journaldb:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      Database: journaldb

  redis:
    image: redis:latest
    container_name: redis_js
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4571:4571"            # LocalStack Edge Proxy
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"