server:
  port: 8081

spring:
  application:
    name: journals
  redis:
    host: localhost
    port: 6379

#  r2dbc:
#    url: r2dbc:postgresql://localhost:5433/journaldb
#    username: postgres
#    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public
    liquibase-schema: public

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

aws:
  access-key-id: test
  secret-access-key: test
  region: us-east-1
  s3:
    bucket-name: curemap-vault
    endpoint: http://localhost:4566
    path-style-access: true

#  AKIARZYETDP3C6EGRZW3
# z8eDQuL9l17INhExCGIC97MjWLj4TEkeaveej/WG

files:
  acceptedImages:
    - ".jpeg"
    - ".jpg"
    - ".png"
  acceptedAudios:
    - ".wav"    # Uncompressed, high quality
    - ".aiff"   # Uncompressed, high quality
    - ".mp3"    # Most common compressed format
    - ".m4a"    # Apple's preferred format
    - ".ogg"    # Open source alternative
    - ".flac"   # Lossless compression
    - ".aac"    # Good quality at lower bitrates
  fileLimits:
    maxImageSizeMB: 5_000_000    # 10MB per image
    maxAudioSizeMB: 50_000_000    # 50MB per audio file

info:
  app:
    name: ${spring.application.name}
    description: "CureMap Journaling Service Application, responsible for user journaling"
    version: "1.0.0"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  instance:
    preferIpAddress: true
    appname: ${spring.application.name}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true